version: '3.8'

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=changeme
    ports:
      - 7017:27017
    volumes:
      - db:/data/db
  server:
    depends_on:
      - mongodb
    build: .
    image: websocket-example
    ports:
      - 80:80
      - 443:443
    environment:
      HTTP_PORT: 80
      HTTPS_PORT: 443
        - DB_HOST=localhost
        - DB_USER=root
        - DB_PASSWORD=changeme
        - DB_NAME=example
        - DB_PORT=27017

volumes:
  db:
